server:
  port: 8080

spring:
  application:
    name: tutor-student-mediator
  
  datasource:
    url: jdbc:mysql://localhost:3306/tutor_connect?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Pradhan407
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:

    hibernate:
      ddl-auto: update

    show-sql: true

    open-in-view: false

    properties:
      hibernate:

        format_sql: true

        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never
  
logging:
  level:
  org.hibernate.SQL: DEBUG
  org.hibernate.orm.jdbc.bind: TRACE

app:
  jwt:
    secret: 4f6e7954686973497341566572794c6f6e675365637265744b6579466f724a5754
    expiration-ms: 86400000